### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by gamatacy** [GeruniaSun/ITMO-programming-lab5#1]
Сделать отдельные классы билдера для всех классов

https://github.com/GeruniaSun/ITMO-programming-lab5/blob/4827904d1c76e634f220eb2fd6d7d88706a4cd8a/src/main/java/data/Ticket.java#L45-L98

**Comment by GeruniaSun** [comment]
Сделал TicketBuilder и VenueBuilder в пакете data

ITMO-programming-lab5/src/main/java/data/TicketBuilder.java
