### ISSUE TITLE
Console class

### ISSUE THREAD

**Issue by gamatacy** [GeruniaSun/ITMO-programming-lab5#2]
Сделать отдельный класс для консоли

https://github.com/GeruniaSun/ITMO-programming-lab5/blob/4827904d1c76e634f220eb2fd6d7d88706a4cd8a/src/main/java/commands/Invoker.java#L30C3-L49C10

**Comment by GeruniaSun** [comment]
добавил пакет app в него убрал invoker, reciever, main. В нем же сделал новый класс AppConsole
