### ISSUE TITLE
Implement collection manager to store ticket set

### ISSUE THREAD

**Issue by gamatacy** [GeruniaSun/ITMO-programming-lab5#3]
Хранить коллекцию лучше в отдельном классе 

https://github.com/GeruniaSun/ITMO-programming-lab5/blob/4827904d1c76e634f220eb2fd6d7d88706a4cd8a/src/main/java/Main.java#L27C1-L28C1

**Comment by GeruniaSun** [comment]
добавил в пакет app класс Storage
